//$file${.::bsp.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: blinky_console.qm
// File:  ${.::bsp.cpp}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::bsp.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpcpp.hpp"  // QP/C++ framework API
#include "bsp.hpp"    // Board Support Package interface
#include <iostream>   // for cout/cerr
#include <cstdlib>    // for exit()

#if (QP_VERSION < 800U)
#error this application requires qp version 8.0.0 or higher
#endif

#ifdef Q_SPY
#error Simple Blinky Application does not support QP/Spy software tracing
#endif

//============================================================================
namespace { // unnamed namespace for local stuff with internal linkage

Q_DEFINE_THIS_FILE

} // unnamed namespace

//============================================================================
// Error handler and ISRs...

extern "C" {

//............................................................................
void Q_onError(char const * const module, int id) {
    std::cerr << "Assertion failed in " << module << ':' << id << std::endl;
    exit(-1);
}
//............................................................................
void assert_failed(char const * const module, int_t const id); // prototype
void assert_failed(char const * const module, int_t const id) {
    Q_onError(module, id);
}

} // extern "C"

//============================================================================
namespace BSP {

void init() {
    std::cout << "Simple Blinky example\n"
            "QP/C++ version: " QP_VERSION_STR "\n"
            "Press Ctrl-C to quit..." << std::endl;
}
//............................................................................
void start() {
    // no need to initialize event pools
    //QP::QF::poolInit(smlPoolSto, sizeof(smlPoolSto), sizeof(smlPoolSto[0]));

    // no need to initialize publish-subscribe
    //static QP::QSubscrList subscrSto[APP::MAX_PUB_SIG];
    //QP::QActive::psInit(subscrSto, Q_DIM(subscrSto));

    // start AOs...
    static QP::QEvt const *blinkyQueueSto[10];
    APP::AO_Blinky->start(
        1U,                          // QP prio. of the AO
        blinkyQueueSto,              // event queue storage
        Q_DIM(blinkyQueueSto),       // queue length [events]
        nullptr, 0U);                // no stack storage
}
//............................................................................
void ledOn() {
    std::cout << "LED-ON" << std::endl;
}
//............................................................................
void ledOff() {
    std::cout << "LED-OFF" << std::endl;
}
//............................................................................
void terminate(int16_t result) {
    Q_UNUSED_PAR(result);
}

} // namespace BSP

//============================================================================
namespace QP {

// QF callbacks...
void QF::onStartup() {
}
//............................................................................
void QF::onCleanup() {
}
//............................................................................
void QF::onClockTick(void) {
    QTimeEvt::TICK_X(0U, nullptr);  // QTimeEvt clock tick processing
}

} // namespace QP
