//$file${.::philo.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: dpp-comp.qm
// File:  ${.::philo.cpp}
//
// This code has been generated by QM 7.0.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::philo.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpcpp.hpp"           // QP/C++ real-time event framework
#include "bsp.hpp"             // Board Support Package
#include "app.hpp"             // Application interface

//$declare${Comp::Philo} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${Comp::Philo} .............................................................
class Philo : public QP::QMsm {
public:
    static std::array<Philo, N_PHILO> inst;

private:
    CompTimeEvt m_timeEvt;
    friend class Table;

public:
    Philo();
    std::uint8_t getId() {
        return static_cast<std::uint8_t>(this - &APP::Philo::inst[0]);
    }

protected:
    QM_STATE_DECL( initial);
    QM_STATE_DECL( thinking);
    QM_ACTION_DECL(thinking_e);
    QM_ACTION_DECL(thinking_x);
    QM_STATE_DECL( hungry);
    QM_ACTION_DECL(hungry_e);
    QM_STATE_DECL( eating);
    QM_ACTION_DECL(eating_e);
    QM_ACTION_DECL(eating_x);
}; // class Philo

} // namespace APP
//$enddecl${Comp::Philo} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//----------------------------------------------------------------------------
namespace { // unnamed namespace for local definitions with internal linkage

//Q_DEFINE_THIS_FILE

// helper function to provide a randomized think time for Philos
static inline QP::QTimeEvtCtr think_time() {
    return static_cast<QP::QTimeEvtCtr>((BSP::random() % BSP::TICKS_PER_SEC)
                                        + (BSP::TICKS_PER_SEC/2U));
}

// helper function to provide a randomized eat time for Philos
static inline QP::QTimeEvtCtr eat_time() {
    return static_cast<QP::QTimeEvtCtr>((BSP::random() % BSP::TICKS_PER_SEC)
                                        + BSP::TICKS_PER_SEC);
}

} // unnamed namespace

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 800U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpcpp version 8.0.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Comp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${Comp::CompTimeEvt} .......................................................

//${Comp::CompTimeEvt::CompTimeEvt} ..........................................
CompTimeEvt::CompTimeEvt(
    QP::QActive * act,
    std::uint16_t num,
    QP::QSignal const sig,
    std::uint_fast8_t const tickRate)
  : QTimeEvt(act, sig, tickRate),
    compNum(num)
{}

//${Comp::Philo} .............................................................
std::array<Philo, N_PHILO> Philo::inst;

//${Comp::Philo::Philo} ......................................................
Philo::Philo()
  : QMsm(&initial),
    m_timeEvt(AO_Table, getId(), TIMEOUT_SIG, 0U)
{}

//${Comp::Philo::SM} .........................................................
QM_STATE_DEF(Philo, initial) {
    //${Comp::Philo::SM::initial}
    static_cast<void>(e); // unused parameter

    #ifdef Q_SPY
    std::uint8_t n = getId();
    QS_OBJ_ARR_DICTIONARY(&Philo::inst[n], n);
    QS_OBJ_ARR_DICTIONARY(&Philo::inst[n].m_timeEvt, n);
    #endif

    static bool registered = false;
    if (!registered) {
        registered = true;
        QS_FUN_DICTIONARY(&Philo::initial);
        QS_FUN_DICTIONARY(&Philo::thinking);
        QS_FUN_DICTIONARY(&Philo::hungry);
        QS_FUN_DICTIONARY(&Philo::eating);
    }

    static constexpr struct {
        QP::QMState const *target;
        std::array<QP::QActionHandler, 2> act;
    } tatbl_ = { // tran-action table
        &thinking_s, // target state
        {
            &thinking_e, // entry
            Q_ACTION_NULL // zero terminator
        }
    };
    return qm_tran_init(&tatbl_);
}

//${Comp::Philo::SM::thinking} ...............................................
QP::QMState const Philo::thinking_s = {
    QM_STATE_NULL, // superstate (top)
    &Philo::thinking,
    &Philo::thinking_e,
    &Philo::thinking_x,
    Q_ACTION_NULL  // no initial tran.
};
//${Comp::Philo::SM::thinking}
QM_ACTION_DEF(Philo, thinking_e) {
    m_timeEvt.armX(think_time(), 0U);
    return qm_entry(&thinking_s);
}
//${Comp::Philo::SM::thinking}
QM_ACTION_DEF(Philo, thinking_x) {
    static_cast<void>(m_timeEvt.disarm());
    return qm_exit(&thinking_s);
}
//${Comp::Philo::SM::thinking}
QM_STATE_DEF(Philo, thinking) {
    QP::QState status_;
    switch (e->sig) {
        //${Comp::Philo::SM::thinking::TIMEOUT}
        case TIMEOUT_SIG: {

            static constexpr struct {
                QP::QMState const *target;
                std::array<QP::QActionHandler, 3> act;
            } tatbl_ = { // tran-action table
                &hungry_s, // target state
                {
                    &thinking_x, // exit
                    &hungry_e, // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = qm_tran(&tatbl_);
            break;
        }
        //${Comp::Philo::SM::thinking::TEST}
        case TEST_SIG: {
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = Q_RET_SUPER;
            break;
        }
    }
    return status_;
}

//${Comp::Philo::SM::hungry} .................................................
QP::QMState const Philo::hungry_s = {
    QM_STATE_NULL, // superstate (top)
    &Philo::hungry,
    &Philo::hungry_e,
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${Comp::Philo::SM::hungry}
QM_ACTION_DEF(Philo, hungry_e) {
    #ifdef QEVT_PAR_INIT
    TableEvt const *pe = QP::QF::q_new<TableEvt>(HUNGRY_SIG, getId());
    #else
    TableEvt *pe = QP::QF::q_new<TableEvt>(HUNGRY_SIG);
    pe->philoId = getId();
    #endif
    AO_Table->postLIFO(pe);
    return qm_entry(&hungry_s);
}
//${Comp::Philo::SM::hungry}
QM_STATE_DEF(Philo, hungry) {
    QP::QState status_;
    switch (e->sig) {
        //${Comp::Philo::SM::hungry::EAT}
        case EAT_SIG: {

            static constexpr struct {
                QP::QMState const *target;
                std::array<QP::QActionHandler, 2> act;
            } tatbl_ = { // tran-action table
                &eating_s, // target state
                {
                    &eating_e, // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = qm_tran(&tatbl_);
            break;
        }
        default: {
            status_ = Q_RET_SUPER;
            break;
        }
    }
    return status_;
}

//${Comp::Philo::SM::eating} .................................................
QP::QMState const Philo::eating_s = {
    QM_STATE_NULL, // superstate (top)
    &Philo::eating,
    &Philo::eating_e,
    &Philo::eating_x,
    Q_ACTION_NULL  // no initial tran.
};
//${Comp::Philo::SM::eating}
QM_ACTION_DEF(Philo, eating_e) {
    m_timeEvt.armX(eat_time(), 0U);
    return qm_entry(&eating_s);
}
//${Comp::Philo::SM::eating}
QM_ACTION_DEF(Philo, eating_x) {
    m_timeEvt.disarm();

    // asynchronously post event to the Container
    #ifdef QEVT_PAR_INIT
    TableEvt const *pe = QP::QF::q_new<TableEvt>(DONE_SIG, getId());
    #else
    TableEvt *pe = QP::QF::q_new<TableEvt>(DONE_SIG);
    pe->philoId = getId();
    #endif
    AO_Table->postLIFO(pe);
    return qm_exit(&eating_s);
}
//${Comp::Philo::SM::eating}
QM_STATE_DEF(Philo, eating) {
    QP::QState status_;
    switch (e->sig) {
        //${Comp::Philo::SM::eating::TIMEOUT}
        case TIMEOUT_SIG: {

            static constexpr struct {
                QP::QMState const *target;
                std::array<QP::QActionHandler, 3> act;
            } tatbl_ = { // tran-action table
                &thinking_s, // target state
                {
                    &eating_x, // exit
                    &thinking_e, // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = qm_tran(&tatbl_);
            break;
        }
        default: {
            status_ = Q_RET_SUPER;
            break;
        }
    }
    return status_;
}

//${Comp::SM_Philo} ..........................................................
std::array<QP::QAsm * const, N_PHILO> SM_Philo = { // opaque pointers to Philo instances
    &Philo::inst[0],
    &Philo::inst[1],
    &Philo::inst[2],
    &Philo::inst[3],
    &Philo::inst[4]
};

} // namespace APP
//$enddef${Comp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
