//$file${.::reminder2.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: reminder2.qm
// File:  ${.::reminder2.cpp}
//
// This code has been generated by QM 7.0.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::reminder2.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpcpp.hpp"    // QP/C++ real-time evetn framework
#include "bsp.hpp"      // Board Support Package
#include "app.hpp"      // Application

namespace {
//Q_DEFINE_THIS_FILE
}

//$declare${AOs::Cruncher} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Cruncher} ...........................................................
class Cruncher : public QP::QActive {
public:
    static Cruncher inst;

private:

    // internal variable
    double m_sum;

public:
    explicit Cruncher() noexcept
      : QActive(Q_STATE_CAST(&initial))
    {}

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(processing);
    Q_STATE_DECL(final);
}; // class Cruncher
//$enddecl${AOs::Cruncher} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 800U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpcpp version 8.0.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${App} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${App::ReminderEvt} ........................................................

//${App::AO_Cruncher} ........................................................
QP::QActive * const AO_Cruncher = &Cruncher::inst;
//$enddef${App} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Cruncher} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Cruncher} ...........................................................
Cruncher Cruncher::inst;

//${AOs::Cruncher::SM} .......................................................
Q_STATE_DEF(Cruncher, initial) {
    //${AOs::Cruncher::SM::initial}
    Q_UNUSED_PAR(e);
    return tran(&processing);
}

//${AOs::Cruncher::SM::processing} ...........................................
Q_STATE_DEF(Cruncher, processing) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Cruncher::SM::processing}
        case Q_ENTRY_SIG: {
            #ifdef QEVT_PAR_INIT
            ReminderEvt const *reminder = QP::QF::q_new<ReminderEvt>(CRUNCH_SIG, 0U);
            #else
            ReminderEvt *reminder = QP::QF::q_new<ReminderEvt>(CRUNCH_SIG);
            reminder->iter = 0U;
            #endif

            POST(reminder, this);
            m_sum = 0.0;
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Cruncher::SM::processing::CRUNCH}
        case CRUNCH_SIG: {
            std::uint32_t n = Q_EVT_CAST(ReminderEvt)->iter;
            std::uint32_t const iter = n + 100U;
            for (; n < iter; ++n) {
                if ((n & 1U) == 0U) {
                    m_sum += 1.0/(2U*n + 1U);
                }
                else {
                    m_sum -= 1.0/(2U*n + 1U);
                }
            }
            //${AOs::Cruncher::SM::processing::CRUNCH::[iter<0x07000000U]}
            if (iter < 0x07000000U) {
                #ifdef QEVT_PAR_INIT
                ReminderEvt const *reminder = QP::QF::q_new<ReminderEvt>(CRUNCH_SIG, iter);
                #else
                ReminderEvt *reminder = QP::QF::q_new<ReminderEvt>(CRUNCH_SIG);
                reminder->iter = iter;
                #endif

                POST(reminder, this);
                status_ = Q_RET_HANDLED;
            }
            //${AOs::Cruncher::SM::processing::CRUNCH::[else]}
            else {
                BSP::showMsg("pi=", 4.0*m_sum);
                status_ = tran(&processing);
            }
            break;
        }
        //${AOs::Cruncher::SM::processing::ECHO}
        case ECHO_SIG: {
            BSP::showMsg("Echo! pi=", 4.0*m_sum);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Cruncher::SM::processing::TERMINATE}
        case TERMINATE_SIG: {
            status_ = tran(&final);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${AOs::Cruncher::SM::final} ................................................
Q_STATE_DEF(Cruncher, final) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Cruncher::SM::final}
        case Q_ENTRY_SIG: {
            BSP::showMsg("final-ENTRY;", 0.0);
            QP::QF::stop(); // terminate the application
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Cruncher} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
