//$file${.::bsp.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: blinky.qm
// File:  ${.::bsp.cpp}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::bsp.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpcpp.hpp"        // QP/C++ real-time embedded framework
#include "bsp.hpp"          // Board Support Package
#include "app.hpp"          // Application

#include <iostream>         // for cout/cerr
#include <cstdlib>          // for exit()

#if (QP_VERSION < 800U)
#error this application requires qpcpp version 8.0.0 or higher
#endif

#ifdef Q_SPY
#error Simple Blinky Application does not support QP/Spy software tracing
#endif

//============================================================================
namespace { // unnamed namespace for local stuff with internal linkage

Q_DEFINE_THIS_FILE

} // unnamed namespace

//============================================================================
extern "C" {

//............................................................................
Q_NORETURN Q_onError(char const * const module, int_t id) {
    std::cerr << "ERROR in " << module << ':' << id << std::endl;
    QP::QF::onCleanup();
    QS_EXIT();
    exit(-1);
}

} // extern "C"

//============================================================================
namespace BSP {

//............................................................................
void init(int argc, char *argv[]) {
    Q_UNUSED_PAR(argc);
    Q_UNUSED_PAR(argv);

    std::cout << "Simple Blinky example\n"
            "QP/C++ version: " QP_VERSION_STR "\n"
            "Press Ctrl-C to quit..." << std::endl;

    // mutable events not used -- no need to call QP::QF::poolInit()
    // publish-subscribe not used -- no need to call QP::QActive::psInit()
}
//............................................................................
void ledOn() {
    std::cout << "LED-ON" << std::endl;
}
//............................................................................
void ledOff() {
    std::cout << "LED-OFF" << std::endl;
}

} // namespace BSP

//============================================================================
namespace QP {

// QF callbacks...
void QF::onStartup() {
    // start AOs...
    static QEvtPtr blinkyQueueSto[10];
    APP::AO_Blinky->start(
        1U,                      // QP prio. of the AO
        blinkyQueueSto,          // event queue storage
        Q_DIM(blinkyQueueSto),   // queue length [events]
        nullptr, 0U);            // no stack storage
}
//............................................................................
void QF::onCleanup() {
}
//............................................................................
void QF::onClockTick() {
    QTimeEvt::TICK_X(0U, nullptr);  // QTimeEvt clock tick processing
}

} // namespace QP
