//$file${.::reminder.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: reminder.qm
// File:  ${.::reminder.cpp}
//
// This code has been generated by QM 7.0.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::reminder.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpcpp.hpp"    // QP/C++ real-time event framework
#include "bsp.hpp"      // Board Support Package
#include "app.hpp"      // Application

//Q_DEFINE_THIS_FILE

//$declare${AOs::Sensor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Sensor} .............................................................
class Sensor : public QP::QActive {
public:
    static Sensor inst;
    QP::QTimeEvt m_timeEvt;
    std::uint16_t m_pollCtr;
    std::uint16_t m_procCtr;

public:
    Sensor();

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(final);
    Q_STATE_DECL(polling);
    Q_STATE_DECL(processing);
    Q_STATE_DECL(idle);
    Q_STATE_DECL(busy);
}; // class Sensor
//$enddecl${AOs::Sensor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 800U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpcpp version 8.0.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${App} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${App::ReminderEvt} ........................................................

//${App::AO_Sensor} ..........................................................
QP::QActive * const AO_Sensor = &Sensor::inst;
//$enddef${App} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Sensor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Sensor} .............................................................
Sensor Sensor::inst;

//${AOs::Sensor::Sensor} .....................................................
Sensor::Sensor()
  : QP::QActive(Q_STATE_CAST(&initial)),
    m_timeEvt(this, TIMEOUT_SIG, 0U),
    m_pollCtr(0U),
    m_procCtr(0U)
{}

//${AOs::Sensor::SM} .........................................................
Q_STATE_DEF(Sensor, initial) {
    //${AOs::Sensor::SM::initial}
    Q_UNUSED_PAR(e);

    m_pollCtr = 0U;
    m_procCtr = 0U;
    return tran(&polling);
}

//${AOs::Sensor::SM::final} ..................................................
Q_STATE_DEF(Sensor, final) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Sensor::SM::final}
        case Q_ENTRY_SIG: {
            QP::QF::stop(); // terminate the application
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${AOs::Sensor::SM::polling} ................................................
Q_STATE_DEF(Sensor, polling) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Sensor::SM::polling}
        case Q_ENTRY_SIG: {
            // periodic timeout in 1/2 second and every 1/2 second
            m_timeEvt.armX(BSP::TICKS_PER_SEC/2,
                BSP::TICKS_PER_SEC/2);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Sensor::SM::polling}
        case Q_EXIT_SIG: {
            m_timeEvt.disarm();
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Sensor::SM::polling::initial}
        case Q_INIT_SIG: {
            status_ = tran(&processing);
            break;
        }
        //${AOs::Sensor::SM::polling::TIMEOUT}
        case TIMEOUT_SIG: {
            // NOTE: this constant event is statically pre-allocated.
            // It can be posted/published as any other event.
            //
            static const QP::QEvt reminderEvt {DATA_READY_SIG};

            ++m_pollCtr;
            BSP::showMsg("polling ", m_pollCtr);
            if ((m_pollCtr & 0x3U) == 0U) {  // modulo 4
                POST(&reminderEvt, this);
            }
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Sensor::SM::polling::TERMINATE}
        case TERMINATE_SIG: {
            status_ = tran(&final);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${AOs::Sensor::SM::polling::processing} ....................................
Q_STATE_DEF(Sensor, processing) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Sensor::SM::polling::processing::initial}
        case Q_INIT_SIG: {
            status_ = tran(&idle);
            break;
        }
        default: {
            status_ = super(&polling);
            break;
        }
    }
    return status_;
}

//${AOs::Sensor::SM::polling::processing::idle} ..............................
Q_STATE_DEF(Sensor, idle) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Sensor::SM::polling::processing::idle}
        case Q_ENTRY_SIG: {
            BSP::showMsg("idle-ENTRY;", 0U);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Sensor::SM::polling::processing::idle::DATA_READY}
        case DATA_READY_SIG: {
            status_ = tran(&busy);
            break;
        }
        default: {
            status_ = super(&processing);
            break;
        }
    }
    return status_;
}

//${AOs::Sensor::SM::polling::processing::busy} ..............................
Q_STATE_DEF(Sensor, busy) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Sensor::SM::polling::processing::busy}
        case Q_ENTRY_SIG: {
            BSP::showMsg("busy-ENTRY;", 0);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Sensor::SM::polling::processing::busy::TIMEOUT}
        case TIMEOUT_SIG: {
            ++m_procCtr;
            BSP::showMsg("processing ", m_procCtr);
            //${AOs::Sensor::SM::polling::processing::busy::TIMEOUT::[(m_procCtr&0x1U)==0U]}
            if ((m_procCtr & 0x1U) == 0U) {
                status_ = tran(&idle);
            }
            //${AOs::Sensor::SM::polling::processing::busy::TIMEOUT::[else]}
            else {
                status_ = Q_RET_HANDLED;
            }
            break;
        }
        default: {
            status_ = super(&processing);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Sensor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
