//$file${.::tstsm.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: tstsm.qm
// File:  ${.::tstsm.cpp}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
//
// Copyright (C) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                    Q u a n t u m  L e a P s
//                    ------------------------
//                    Modern Embedded Software
//
// SPDX-License-Identifier: LicenseRef-QL-cert
//
// This software is part of the QP/C Certification Kit, which is licensed
// under the terms of the Quantum Leaps Certification Kit licenses. Please
// contact Quantum Leaps for more information about the available licensing
// options.
//
// RESTRICTIONS
// You may NOT:
// (a) redistribute, encumber, sell, rent, lease, sublicense, or otherwise
//     transfer rights in this software,
// (b) remove or alter any trademark, logo, copyright or other proprietary
//     notices, legends, symbols or labels present in this software,
// (c) plagiarize this software to sidestep the licensing obligations.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::tstsm.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpcpp.hpp"   // QP/C++ framework
#include "tstsm.hpp"   // TstSM state machine

namespace {
Q_DEFINE_THIS_FILE
}

//$declare${SMs} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${SMs::TstSM} ..............................................................
class TstSM : public QP::QHsm {
private:
    std::uint8_t m_foo;

public:
    static TstSM inst;

public:
    TstSM();
    friend bool TstSM_isIn(std::uint32_t const state_num);

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(s);
    Q_STATE_DECL(s1);
    Q_STATE_DECL(s11);
    Q_STATE_DECL(s111);
    Q_STATE_DECL(s112);
    Q_STATE_DECL(s12);
    Q_STATE_DECL(s2);
    Q_STATE_DECL(s21);
    Q_STATE_DECL(s211);
    Q_STATE_DECL(s212);
    Q_STATE_DECL(s22);
    Q_STATE_DECL(t);

protected:
    QP::QStateHandler hist_s;
    QP::QStateHandler hist_s1;
    QP::QStateHandler hist_s2;
}; // class TstSM

} // namespace APP
//$enddecl${SMs} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpcpp version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${Shared::the_TstSM} .......................................................
QP::QAsm * const the_TstSM = &TstSM::inst;

//${Shared::TstSM_isIn} ......................................................
bool TstSM_isIn(std::uint32_t const state_num) {
    bool stat = false;
    switch (state_num) {
    case 0:
        stat = the_TstSM->isIn(Q_STATE_CAST(&TstSM::s));
        break;
    case 1:
        stat = the_TstSM->isIn(Q_STATE_CAST(&TstSM::s1));
        break;
    case 11:
        stat = the_TstSM->isIn(Q_STATE_CAST(&TstSM::s11));
        break;
    case 111:
        stat = the_TstSM->isIn(Q_STATE_CAST(&TstSM::s111));
        break;
    case 112:
        stat = the_TstSM->isIn(Q_STATE_CAST(&TstSM::s112));
        break;
    case 12:
        stat = the_TstSM->isIn(Q_STATE_CAST(&TstSM::s12));
        break;
    case 2:
        stat = the_TstSM->isIn(Q_STATE_CAST(&TstSM::s2));
        break;
    case 21:
        stat = the_TstSM->isIn(Q_STATE_CAST(&TstSM::s21));
        break;
    case 211:
        stat = the_TstSM->isIn(Q_STATE_CAST(&TstSM::s211));
        break;
    case 212:
        stat = the_TstSM->isIn(Q_STATE_CAST(&TstSM::s212));
        break;
    case 22:
        stat = the_TstSM->isIn(Q_STATE_CAST(&TstSM::s22));
        break;
    default:
        Q_ERROR();
    }
    return stat;
}

} // namespace APP
//$enddef${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${SMs} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${SMs::TstSM} ..............................................................
TstSM TstSM::inst;

//${SMs::TstSM::TstSM} .......................................................
TstSM::TstSM()
  : QP::QHsm(Q_STATE_CAST(&TstSM::initial))
{}

//${SMs::TstSM::SM} ..........................................................
Q_STATE_DEF(TstSM, initial) {
    //${SMs::TstSM::SM::initial}
    Q_UNUSED_PAR(e);
    m_foo = 0U;
    BSP_display("top-INIT;");
    // state history attributes
    hist_s = &s1;
    hist_s1 = &s11;
    hist_s2 = &s211;

    QS_FUN_DICTIONARY(&TstSM::s);
    QS_FUN_DICTIONARY(&TstSM::s1);
    QS_FUN_DICTIONARY(&TstSM::s11);
    QS_FUN_DICTIONARY(&TstSM::s111);
    QS_FUN_DICTIONARY(&TstSM::s112);
    QS_FUN_DICTIONARY(&TstSM::s12);
    QS_FUN_DICTIONARY(&TstSM::s2);
    QS_FUN_DICTIONARY(&TstSM::s21);
    QS_FUN_DICTIONARY(&TstSM::s211);
    QS_FUN_DICTIONARY(&TstSM::s212);
    QS_FUN_DICTIONARY(&TstSM::s22);
    QS_FUN_DICTIONARY(&TstSM::t);

    return tran(&s2);
}

//${SMs::TstSM::SM::s} .......................................................
Q_STATE_DEF(TstSM, s) {
    QP::QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::s}
        case Q_ENTRY_SIG: {
            BSP_display("s-ENTRY;");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::s}
        case Q_EXIT_SIG: {
            BSP_display("s-EXIT;");
            // save shallow history
            hist_s = childState(&s);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::s::initial}
        case Q_INIT_SIG: {
            BSP_display("s-INIT;");
            status_ = tran(&s1);
            break;
        }
        //${SMs::TstSM::SM::s::E}
        case E_SIG: {
            BSP_display("s-E;");
            status_ = tran(&s21);
            break;
        }
        //${SMs::TstSM::SM::s::I}
        case I_SIG: {
            BSP_display("s-I;");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::s::C}
        case C_SIG: {
            BSP_display("s-C;");
            status_ = tran(&t);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${SMs::TstSM::SM::s::s1} ...................................................
Q_STATE_DEF(TstSM, s1) {
    QP::QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::s::s1}
        case Q_ENTRY_SIG: {
            BSP_display("s1-ENTRY;");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::s::s1}
        case Q_EXIT_SIG: {
            BSP_display("s1-EXIT;");
            // save shallow history
            hist_s1 = childState(&s1);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::s::s1::initial}
        case Q_INIT_SIG: {
            BSP_display("s1-INIT;");
            status_ = tran(&s111);
            break;
        }
        //${SMs::TstSM::SM::s::s1::B}
        case B_SIG: {
            BSP_display("s1-B;");
            status_ = tran(&s12);
            break;
        }
        //${SMs::TstSM::SM::s::s1::F}
        case F_SIG: {
            BSP_display("s1-F;");
            status_ = tran(&s21);
            break;
        }
        //${SMs::TstSM::SM::s::s1::I}
        case I_SIG: {
            //${SMs::TstSM::SM::s::s1::I::[m_foo]}
            if (m_foo) {
                m_foo = 0U;
                BSP_display("s1-I;");
                status_ = Q_RET_HANDLED;
            }
            else {
                status_ = Q_RET_UNHANDLED;
            }
            break;
        }
        default: {
            status_ = super(&s);
            break;
        }
    }
    return status_;
}

//${SMs::TstSM::SM::s::s1::s11} ..............................................
Q_STATE_DEF(TstSM, s11) {
    QP::QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::s::s1::s11}
        case Q_ENTRY_SIG: {
            BSP_display("s11-ENTRY;");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::s::s1::s11}
        case Q_EXIT_SIG: {
            BSP_display("s11-EXIT;");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::s::s1::s11::initial}
        case Q_INIT_SIG: {
            BSP_display("s11-INIT;");
            status_ = tran(&s111);
            break;
        }
        //${SMs::TstSM::SM::s::s1::s11::A}
        case A_SIG: {
            BSP_display("s11-A;");
            status_ = tran(&s11);
            break;
        }
        //${SMs::TstSM::SM::s::s1::s11::D}
        case D_SIG: {
            //${SMs::TstSM::SM::s::s1::s11::D::[!m_foo]}
            if (!m_foo) {
                m_foo = 1U;
                BSP_display("s11-D;");
                status_ = tran(&s1);
            }
            else {
                status_ = Q_RET_UNHANDLED;
            }
            break;
        }
        //${SMs::TstSM::SM::s::s1::s11::G}
        case G_SIG: {
            BSP_display("s11-G->H*-s2;");
            status_ = tran_hist(hist_s2);
            break;
        }
        default: {
            status_ = super(&s1);
            break;
        }
    }
    return status_;
}

//${SMs::TstSM::SM::s::s1::s11::s111} ........................................
Q_STATE_DEF(TstSM, s111) {
    QP::QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::s::s1::s11::s111}
        case Q_ENTRY_SIG: {
            BSP_display("s111-ENTRY;");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::s::s1::s11::s111}
        case Q_EXIT_SIG: {
            BSP_display("s111-EXIT;");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::s::s1::s11::s111::C}
        case C_SIG: {
            BSP_display("s111-C;");
            status_ = tran(&s112);
            break;
        }
        default: {
            status_ = super(&s11);
            break;
        }
    }
    return status_;
}

//${SMs::TstSM::SM::s::s1::s11::s112} ........................................
Q_STATE_DEF(TstSM, s112) {
    QP::QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::s::s1::s11::s112}
        case Q_ENTRY_SIG: {
            BSP_display("s112-ENTRY;");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::s::s1::s11::s112}
        case Q_EXIT_SIG: {
            BSP_display("s112-EXIT;");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::s::s1::s11::s112::H}
        case H_SIG: {
            BSP_display("s112-H;");
            status_ = tran(&s);
            break;
        }
        default: {
            status_ = super(&s11);
            break;
        }
    }
    return status_;
}

//${SMs::TstSM::SM::s::s1::s12} ..............................................
Q_STATE_DEF(TstSM, s12) {
    QP::QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::s::s1::s12}
        case Q_ENTRY_SIG: {
            BSP_display("s12-ENTRY;");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::s::s1::s12}
        case Q_EXIT_SIG: {
            BSP_display("s12-EXIT;");
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&s1);
            break;
        }
    }
    return status_;
}

//${SMs::TstSM::SM::s::s2} ...................................................
Q_STATE_DEF(TstSM, s2) {
    QP::QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::s::s2}
        case Q_ENTRY_SIG: {
            BSP_display("s2-ENTRY;");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::s::s2}
        case Q_EXIT_SIG: {
            BSP_display("s2-EXIT;");
            // save deep history
            hist_s2 = state();
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::s::s2::initial}
        case Q_INIT_SIG: {
            BSP_display("s2-INIT;");
            status_ = tran(&s211);
            break;
        }
        //${SMs::TstSM::SM::s::s2::B}
        case B_SIG: {
            BSP_display("s2-B;");
            status_ = tran(&s22);
            break;
        }
        //${SMs::TstSM::SM::s::s2::F}
        case F_SIG: {
            BSP_display("s2-F;");
            status_ = tran(&s11);
            break;
        }
        //${SMs::TstSM::SM::s::s2::I}
        case I_SIG: {
            //${SMs::TstSM::SM::s::s2::I::[m_foo]}
            if (m_foo) {
                m_foo = 0U;
                BSP_display("s2-I;");
                status_ = Q_RET_HANDLED;
            }
            else {
                status_ = Q_RET_UNHANDLED;
            }
            break;
        }
        default: {
            status_ = super(&s);
            break;
        }
    }
    return status_;
}

//${SMs::TstSM::SM::s::s2::s21} ..............................................
Q_STATE_DEF(TstSM, s21) {
    QP::QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::s::s2::s21}
        case Q_ENTRY_SIG: {
            BSP_display("s21-ENTRY;");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::s::s2::s21}
        case Q_EXIT_SIG: {
            BSP_display("s21-EXIT;");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::s::s2::s21::initial}
        case Q_INIT_SIG: {
            BSP_display("s21-INIT;");
            status_ = tran(&s211);
            break;
        }
        //${SMs::TstSM::SM::s::s2::s21::A}
        case A_SIG: {
            BSP_display("s21-A;");
            status_ = tran(&s21);
            break;
        }
        //${SMs::TstSM::SM::s::s2::s21::D}
        case D_SIG: {
            //${SMs::TstSM::SM::s::s2::s21::D::[!m_foo]}
            if (!m_foo) {
                m_foo = 1U;
                BSP_display("s21-D;");
                status_ = tran(&s2);
            }
            else {
                status_ = Q_RET_UNHANDLED;
            }
            break;
        }
        //${SMs::TstSM::SM::s::s2::s21::G}
        case G_SIG: {
            BSP_display("s21-G->H*-s1;");
            status_ = tran_hist(hist_s1);
            break;
        }
        default: {
            status_ = super(&s2);
            break;
        }
    }
    return status_;
}

//${SMs::TstSM::SM::s::s2::s21::s211} ........................................
Q_STATE_DEF(TstSM, s211) {
    QP::QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::s::s2::s21::s211}
        case Q_ENTRY_SIG: {
            BSP_display("s211-ENTRY;");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::s::s2::s21::s211}
        case Q_EXIT_SIG: {
            BSP_display("s211-EXIT;");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::s::s2::s21::s211::C}
        case C_SIG: {
            BSP_display("s211-C;");
            status_ = tran(&s212);
            break;
        }
        default: {
            status_ = super(&s21);
            break;
        }
    }
    return status_;
}

//${SMs::TstSM::SM::s::s2::s21::s212} ........................................
Q_STATE_DEF(TstSM, s212) {
    QP::QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::s::s2::s21::s212}
        case Q_ENTRY_SIG: {
            BSP_display("s212-ENTRY;");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::s::s2::s21::s212}
        case Q_EXIT_SIG: {
            BSP_display("s212-EXIT;");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::s::s2::s21::s212::H}
        case H_SIG: {
            BSP_display("s212-H;");
            status_ = tran(&s);
            break;
        }
        default: {
            status_ = super(&s21);
            break;
        }
    }
    return status_;
}

//${SMs::TstSM::SM::s::s2::s22} ..............................................
Q_STATE_DEF(TstSM, s22) {
    QP::QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::s::s2::s22}
        case Q_ENTRY_SIG: {
            BSP_display("s22-ENTRY;");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::s::s2::s22}
        case Q_EXIT_SIG: {
            BSP_display("s22-EXIT;");
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&s2);
            break;
        }
    }
    return status_;
}

//${SMs::TstSM::SM::t} .......................................................
Q_STATE_DEF(TstSM, t) {
    QP::QState status_;
    switch (e->sig) {
        //${SMs::TstSM::SM::t}
        case Q_ENTRY_SIG: {
            BSP_display("t-ENTRY;");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::t}
        case Q_EXIT_SIG: {
            BSP_display("t-EXIT;");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${SMs::TstSM::SM::t::C}
        case C_SIG: {
            BSP_display("t-C->H-s;");
            status_ = tran_hist(hist_s);
            break;
        }
        //${SMs::TstSM::SM::t::E}
        case E_SIG: {
            BSP_display("t-E->H*-s2;");
            status_ = tran_hist(hist_s2);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

} // namespace APP
//$enddef${SMs} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
