//$file${.::app.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: game.qm
// File:  ${.::app.hpp}
//
// This code has been generated by QM 7.0.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::app.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef APP_HPP_
#define APP_HPP_

namespace APP {

constexpr std::uint8_t GAME_TUNNEL_WIDTH  {BSP::SCREEN_WIDTH};
constexpr std::int8_t  GAME_TUNNEL_HEIGHT {BSP::SCREEN_HEIGHT - 10};
constexpr std::uint8_t GAME_MINES_MAX       { 5U};
constexpr std::uint8_t GAME_MINES_DIST_MIN  {10U};
constexpr std::uint8_t GAME_SPEED_X         { 1U};
constexpr std::uint8_t GAME_MISSILE_SPEED_X { 2U};
constexpr std::uint8_t GAME_SHIP_X          {10U};
constexpr std::int8_t  GAME_SHIP_Y          {GAME_TUNNEL_HEIGHT / 2};
constexpr std::int8_t  GAME_WALLS_GAP_Y     {50};
constexpr std::int8_t  GAME_WALLS_MIN_GAP_Y {20};

} // namespace APP

// Shared declarations
//$declare${App} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${App::AppSignals} .........................................................
enum AppSignals  : QP::QSignal { // signals used in the game
    TIME_TICK_SIG = QP::Q_USER_SIG, // published from tick ISR
    PLAYER_TRIGGER_SIG, // published by Player (ISR) to trigger the Missile
    PLAYER_QUIT_SIG,    // published by Player (ISR) to quit the game
    GAME_OVER_SIG,      // published by Ship when it finishes exploding

    // insert other published signals here ...
    MAX_PUB_SIG,        // the last published signal

    PLAYER_SHIP_MOVE_SIG, // posted by Player (ISR) to the Ship to move it

    BLINK_TIMEOUT_SIG,  // signal for Tunnel's blink timeout event
    SCREEN_TIMEOUT_SIG, // signal for Tunnel's screen timeout event

    TAKE_OFF_SIG,       // from Tunnel to Ship to grant permission to take off
    HIT_WALL_SIG,       // from Tunnel to Ship when Ship hits the wall
    HIT_MINE_SIG,       // from Mine to Ship or Missile when it hits the mine
    SHIP_IMG_SIG,       // from Ship to the Tunnel to draw and check for hits
    MISSILE_IMG_SIG,    // from Missile the Tunnel to draw and check for hits
    MINE_IMG_SIG,       // sent by Mine to the Tunnel to draw the mine
    MISSILE_FIRE_SIG,   // sent by Ship to the Missile to fire
    DESTROYED_MINE_SIG, // from Missile to Ship when Missile destroyed Mine
    EXPLOSION_SIG,      // from any exploding object to render the explosion
    MINE_PLANT_SIG,     // from Tunnel to the Mine to plant it
    MINE_DISABLED_SIG,  // from Mine to Tunnel when it becomes disabled
    MINE_RECYCLE_SIG,   // sent by Tunnel to Mine to recycle the mine
    SCORE_SIG,          // from Ship to Tunnel to display the score

    MAX_SIG             // the last signal (keep always last)
};

//${App::GameBitmapIds} ......................................................
enum GameBitmapIds   : std::uint8_t {
    SHIP_BMP,
    MISSILE_BMP,
    MINE1_BMP,
    MINE2_BMP,
    MINE2_MISSILE_BMP,
    EXPLOSION0_BMP,
    EXPLOSION1_BMP,
    EXPLOSION2_BMP,
    EXPLOSION3_BMP,
    MAX_BMP
};

//${App::ObjectPosEvt} .......................................................
class ObjectPosEvt : public QP::QEvt {
public:
    std::uint8_t x;
    std::uint8_t y;

public:
    constexpr ObjectPosEvt(
        QP::QSignal sig,
        std::uint8_t const x0,
        std::uint8_t const y0)
      : QEvt(sig),
        x(x0),
        y(y0)
    {}
}; // class ObjectPosEvt

//${App::ObjectImageEvt} .....................................................
class ObjectImageEvt : public QP::QEvt {
public:
    std::uint8_t x;
    std::int8_t y;
    std::uint8_t bmp;
}; // class ObjectImageEvt

//${App::MineEvt} ............................................................
class MineEvt : public QP::QEvt {
public:
    std::uint8_t id;

public:
    constexpr MineEvt(
        QP::QSignal sig,
        std::uint8_t id_p)
     : QEvt(sig),
       id(id_p)
    {}
}; // class MineEvt

//${App::ScoreEvt} ...........................................................
class ScoreEvt : public QP::QEvt {
public:
    std::uint16_t score;

public:
    constexpr ScoreEvt(
        QP::QSignal sig,
        std::uint16_t score_p)
     : QEvt(sig),
       score(score_p)
    {}
}; // class ScoreEvt

//${App::AO_Tunnel} ..........................................................
// opaque pointer
extern QP::QActive * const AO_Tunnel;

//${App::AO_Ship} ............................................................
// opaque pointer
extern QP::QActive * const AO_Ship;

//${App::AO_Missile} .........................................................
// opaque pointer
extern QP::QActive * const AO_Missile;

//${App::Mine1_getInst} ......................................................
QP::QAsm * Mine1_getInst(std::uint8_t id);

//${App::Mine2_getInst} ......................................................
QP::QAsm * Mine2_getInst(std::uint8_t id);

//${App::QTicker_inst0} ......................................................
extern QP::QTicker QTicker_inst0;

} // namespace APP
//$enddecl${App} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif  // APP_HPP_
