//$file${.::defer.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: defer.qm
// File:  ${.::defer.cpp}
//
// This code has been generated by QM 7.0.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::defer.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpcpp.hpp"   // QP/C++ real-time event framework
#include "bsp.hpp"     // Board Support Package interface
#include "app.hpp"     // Application

namespace {
Q_DEFINE_THIS_FILE
}

//$declare${AOs::TServer} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::TServer} ............................................................
class TServer : public QP::QActive {
public:
    static TServer inst;

private:

    // native QF queue for deferred request events
    QP::QEQueue m_requestQueue;

    // storage for the deferred queue buffer
    QP::QEvtPtr m_requestQSto[3];

    // request event being processed
    RequestEvt const * m_activeRequest;

    // private time event generator
    QP::QTimeEvt m_receivedEvt;

    // private time event generator
    QP::QTimeEvt m_authorizedEvt;

public:
    explicit TServer() noexcept
      : QActive(Q_STATE_CAST(&initial)),
        m_receivedEvt(this, RECEIVED_SIG),
        m_authorizedEvt(this, AUTHORIZED_SIG)
    {
        m_requestQueue.init(m_requestQSto, Q_DIM(m_requestQSto));
    }

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(idle);
    Q_STATE_DECL(busy);
    Q_STATE_DECL(receiving);
    Q_STATE_DECL(authorizing);
    Q_STATE_DECL(final);
}; // class TServer
//$enddecl${AOs::TServer} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 800U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpcpp version 8.0.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${App} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${App::AO_TServer} .........................................................
QP::QActive * const AO_TServer = &TServer::inst;
//$enddef${App} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::TServer} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::TServer} ............................................................
TServer TServer::inst;

//${AOs::TServer::SM} ........................................................
Q_STATE_DEF(TServer, initial) {
    //${AOs::TServer::SM::initial}
    (void)e; // unused parameter
    m_activeRequest = nullptr; // no active request yet

    QS_OBJ_DICTIONARY(&TServer::inst);
    QS_OBJ_DICTIONARY(&TServer::inst.m_receivedEvt);
    QS_OBJ_DICTIONARY(&TServer::inst.m_authorizedEvt);
    QS_OBJ_DICTIONARY(&TServer::inst.m_requestQueue);

    QS_FUN_DICTIONARY(&TServer::idle);
    QS_FUN_DICTIONARY(&TServer::busy);
    QS_FUN_DICTIONARY(&TServer::receiving);
    QS_FUN_DICTIONARY(&TServer::authorizing);
    QS_FUN_DICTIONARY(&TServer::final);

    return tran(&idle);
}

//${AOs::TServer::SM::idle} ..................................................
Q_STATE_DEF(TServer, idle) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::TServer::SM::idle}
        case Q_ENTRY_SIG: {
            BSP::showMsg("idle-ENTRY;", 0U);

            // recall the oldest deferred request...
            if (recall(&m_requestQueue)) {
                BSP::showMsg("Request recalled", 0U);
            }
            else {
                BSP::showMsg("No deferred requests", 0U);
            }
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::TServer::SM::idle::NEW_REQUEST}
        case NEW_REQUEST_SIG: {
            // create and save a new reference to the request event so that
            // this event will be available beyond this RTC step and won't be
            // recycled.
            QP::QF::q_new_ref<RequestEvt>(e, m_activeRequest);

            BSP::showMsg("Processing request #",
                m_activeRequest->ref_num);
            status_ = tran(&receiving);
            break;
        }
        //${AOs::TServer::SM::idle::TERMINATE}
        case TERMINATE_SIG: {
            status_ = tran(&final);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${AOs::TServer::SM::busy} ..................................................
Q_STATE_DEF(TServer, busy) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::TServer::SM::busy}
        case Q_EXIT_SIG: {
            BSP::showMsg("busy-EXIT; done processing request #",
                m_activeRequest->ref_num);

            // delete the reference to the active request, because
            // it is now processed.
            Q_DELETE_REF(m_activeRequest);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::TServer::SM::busy::NEW_REQUEST}
        case NEW_REQUEST_SIG: {
            // defer the new request event...
            if (defer(&m_requestQueue, e)) {
                BSP::showMsg("Deferred request #",
                    Q_EVT_CAST(RequestEvt)->ref_num);
            }
            else { // deferred queue full
                // option1: ignore the new request and do nothing here

                // option2:
                // flush the oldest request to make room for the new one
                QP::QEvt const *old_evt = m_requestQueue.get(0U);
                Q_ASSERT(old_evt != nullptr);
                BSP::showMsg("DISCARDED previous request #",
                    ((RequestEvt*)old_evt)->ref_num);
                QP::QF::gc(old_evt); // explicitly recycle old

                // repeat the defer request after making room in the queue
                if (!defer(&m_requestQueue, e)) {
                    Q_ERROR(); // now it must succeed
                }
            }
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::TServer::SM::busy::TERMINATE}
        case TERMINATE_SIG: {
            status_ = tran(&final);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${AOs::TServer::SM::busy::receiving} .......................................
Q_STATE_DEF(TServer, receiving) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::TServer::SM::busy::receiving}
        case Q_ENTRY_SIG: {
            // inform about the first stage of processing of the request...
            BSP::showMsg("receiving-ENTRY; active request: #",
                m_activeRequest->ref_num);

            // one-shot timeout in 1 second
            m_receivedEvt.armX(BSP::TICKS_PER_SEC, 0U);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::TServer::SM::busy::receiving}
        case Q_EXIT_SIG: {
            m_receivedEvt.disarm();
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::TServer::SM::busy::receiving::RECEIVED}
        case RECEIVED_SIG: {
            status_ = tran(&authorizing);
            break;
        }
        default: {
            status_ = super(&busy);
            break;
        }
    }
    return status_;
}

//${AOs::TServer::SM::busy::authorizing} .....................................
Q_STATE_DEF(TServer, authorizing) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::TServer::SM::busy::authorizing}
        case Q_ENTRY_SIG: {
            // inform about the second stage of processing of the request..
            BSP::showMsg("authorizing-ENTRY; active request: #",
                m_activeRequest->ref_num);

            // one-shot timeout in 2 seconds
            m_authorizedEvt.armX(2U*BSP::TICKS_PER_SEC, 0U);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::TServer::SM::busy::authorizing}
        case Q_EXIT_SIG: {
            m_authorizedEvt.disarm();
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::TServer::SM::busy::authorizing::AUTHORIZED}
        case AUTHORIZED_SIG: {
            status_ = tran(&idle);
            break;
        }
        default: {
            status_ = super(&busy);
            break;
        }
    }
    return status_;
}

//${AOs::TServer::SM::final} .................................................
Q_STATE_DEF(TServer, final) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::TServer::SM::final}
        case Q_ENTRY_SIG: {
            BSP::showMsg("final-ENTRY;", 0U);
            QP::QF::stop(); // terminate the application
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::TServer} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
