//$file${.::bsp.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: game.qm
// File:  ${.::bsp.hpp}
//
// This code has been generated by QM 7.0.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::bsp.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef BSP_HPP_
#define BSP_HPP_

namespace BSP {

constexpr std::uint32_t TICKS_PER_SEC { 33U};
constexpr std::uint32_t SCREEN_WIDTH  {128U};
constexpr std::uint32_t SCREEN_HEIGHT {128U};

void init(void const * const arg);
void terminate(std::int16_t result);

void updateScreen();
void clearFB();
void clearWalls();
void paintString(std::uint8_t x, std::uint8_t y, char const *str);
void paintBitmap(std::uint8_t x, std::uint8_t y, std::uint8_t bmp_id);
void advanceWalls(std::uint8_t top, std::uint8_t bottom);
void updateScore(std::uint16_t score);

bool isThrottle(void); // is the throttle button depressed?
bool doBitmapsOverlap(
    std::uint8_t bmp_id1, std::uint8_t x1, std::uint8_t y1,
    std::uint8_t bmp_id2, std::uint8_t x2, std::uint8_t y2);
bool isWallHit(std::uint8_t bmp_id, std::uint8_t x, std::uint8_t y);
void displayOn();
void displayOff();

void randomSeed(std::uint32_t seed);
std::uint32_t random();

} // namespace BSP

#endif // BSP_HPP_
